### ISSUE TITLE
3 | Longest Substring Without Repeating Characters | C++

### ISSUE THREAD

**Issue by SSKale1** [SHY-Corp/LeetCode-Solutions#9] opened 2020-10-05 18:19 UTC
## **`Title`** - 3. Longest Substring Without Repeating Characters 

**What will change** -
Added Code
### Type of Issue -
- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by VIPUL662** [comment] 2020-10-05 18:48
i want to solve this issue please provide me.

**Comment by SSKale1** [comment] 2020-10-05 18:52
- [x] Assigning to @VIPUL662 .

**Comment by VIPUL662** [comment] 2020-10-05 19:18
i have solved please check.
[longest_substring.zip](https://github.com/SHY-Corp/LeetCode-Solutions/files/5329604/longest_substring.zip)

**Comment by SSKale1** [comment] 2020-10-05 19:25
@VIPUL662 We can't add this to the Repo. You will have to make a Pull Request. Go through the contribution guidelines, contact us if you need any help.

**Comment by aditsawant** [comment] 2020-10-06 11:18
If the issue is still unresolved, I'd love to help out!
Please assign it to me, thanks!

**Closed** 2020-10-06 15:40 UTC
Labels: good first issue, hacktoberfest
