### ISSUE TITLE
1480 | Running Sum of 1D Array | JAVA

### ISSUE THREAD

**Issue by JOKUE2002** [SHY-Corp/LeetCode-Solutions#10] opened 2020-10-05 18:48 UTC
## **`Add 1480`** -

**What will change** -

The solution to challenge 1480 in java language

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by JOKUE2002** [comment] 2020-10-05 18:50
Does anyone want this issue? Otherwise I would submit my solution to the challenge.

**Comment by atingarg1406** [comment] 2020-10-05 18:53
I would like to do this task. Do assign me for this.

**Comment by SSKale1** [comment] 2020-10-05 18:59
- [x] Assigning to @atingarg1406 .
Make sure you read and follow the contribution guidelines. And submit according to the Leetcode Solution with proper Comments explaining the program and Time/Space Complexities if Applicable. And make changes in the correct folder.

**Comment by aditsawant** [comment] 2020-10-06 11:26
If the issue is unresolved, I'd love to help

**Comment by JOKUE2002** [comment] 2020-10-06 11:29
Please give @atingarg1406 some time to solve this issue and create a pull request before asking for it.

In the mean time you could create an own issue for a coding-challenge that sparks your interest.

**Closed** 2020-10-07 03:52 UTC
Labels: good first issue, hacktoberfest
