### ISSUE TITLE
33 | Search in Rotated Sorted Array | Java

### ISSUE THREAD

**Issue by TakuHazard** [SHY-Corp/LeetCode-Solutions#1271] opened 2020-10-28 02:04 UTC
## **`Search in Rotated Sorted Array`** -

**Adding a new leetcode problem with optimized Java solution that utilizes binary search** -

### Type of Issue -

Please add/delete options that are not relevant.
- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by TakuHazard** [comment] 2020-10-28 02:04
Could you please assign this issue to me ?

**Comment by NikhilTaneja98** [comment] 2020-10-28 16:57
Could you assign me this issue?

**Comment by prantoran** [comment] 2020-10-29 07:09
Could you assign this issue to me ?

**Comment by manilal-1084** [comment] 2020-10-29 21:55
Could you please assign this issue to me?

**Comment by SSKale1** [comment] 2020-10-30 14:31
Duplicate of issue #700

**Closed by SSKale1** 2020-10-30 14:31 UTC
Labels: good first issue, hacktoberfest
