### ISSUE TITLE
27 | RemoveElement.cpp | Python

### ISSUE THREAD

**Issue by Piyush228** [SHY-Corp/LeetCode-Solutions#815] opened 2020-10-20 19:40 UTC
## RemoveElement

**What will change** -
Add code to python language

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Add Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Piyush228** [comment] 2020-10-20 19:41
can you assign me?

**Comment by SSKale1** [comment] 2020-10-21 05:42
@Piyush228 This problem already exists in the codebase.

**Comment by Piyush228** [comment] 2020-10-21 05:57
sir can we put this code in different language like python and java
if yes please assign me

**Comment by SSKale1** [comment] 2020-10-21 06:00
The problem currently does not exist in python. If you could create a new Issue or change the title of the current issue to Python I'll assign it to you.

**Comment by Piyush228** [comment] 2020-10-21 06:17
sir I edit this issue , please assign this to me

**Comment by SSKale1** [comment] 2020-10-22 05:52
The issue is already in C++, for editing the issue you need to change the title of the issue to Python from C++

**Comment by SSKale1** [comment] 2020-10-22 05:53
I've done it myself. You can work on this now.

**Closed** 2020-10-22 06:59 UTC
Labels: good first issue, hacktoberfest
