### ISSUE TITLE
1470 | Shuffle the Array | C++

### ISSUE THREAD

**Issue by shivanshuman021** [SHY-Corp/LeetCode-Solutions#719] opened 2020-10-19 10:38 UTC
## **`Shuffle The Array`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by shivanshuman021** [comment] 2020-10-19 10:38
Please assign me this issue . I would like to contribute .
Thanks !

**Comment by rahul975337** [comment] 2020-10-19 18:23
please assign this to me

**Comment by shivanshuman021** [comment] 2020-10-21 00:56
@SSKale1  Please assign it to me . Should I withdraw pull request then again submit after getting assigned ?

**Comment by SSKale1** [comment] 2020-10-21 05:21
@shivanshuman021 It was invalid coz you had not been assigned to the issue. An now the issue is being closed because this problem already exists in the codebase.

**Closed by SSKale1** 2020-10-21 05:21 UTC
Labels: good first issue, hacktoberfest
