### ISSUE TITLE
85. | Maximal Rectangle | C++

### ISSUE THREAD

**Issue by jatin831** [SHY-Corp/LeetCode-Solutions#513] opened 2020-10-18 01:32 UTC
## **Maximal Rectangle** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by swaingotnochill** [comment] 2020-10-18 04:19
Unless the issue is assigned to you, you should not make a PR. This is treated as spam.

**Comment by DEBADRIBASAK** [comment] 2020-10-18 05:33
Please assign this issue to me

**Comment by DEBADRIBASAK** [comment] 2020-10-18 08:57
I have already made a PR. Please assign this issue and approve my request

**Comment by jatin831** [comment] 2020-10-18 10:13
So assign some issue for me. I will do it.

**Closed** 2020-10-18 15:21 UTC
Labels: good first issue, hacktoberfest
